= compactor(1)
Jim Hague, Sinodun Internet Technologies
:manmanual: DNS-STATS
:mansource: DNS-STATS
:man-linkstyle: blue R <>

== NAME

compactor - capture DNS traffic and write query/response pair information to file

== SYNOPSIS

*compactor* ['OPTIONS']... ['FILE'...]

== DESCRIPTION

*compactor* reads DNS traffic, extracts query and response messages and matches
these into query/response pairs. Information on these pairs is written to output file.
Optionally other output files may be written containing all packets, or packets not used
in the matching process. These output files are in PCAP format.

If any input files are specified, *compactor* reads from each input file in turn. The input
files must be in PCAP format. Reading an input file requires no special privileges.

If no input files are specified, but a network interface device is
specified, *compactor* will capture packets from that interface until
interrupted by a SIGINT signal (e.g. from control-C) or a SIGTERM
signal (e.g. generated by the *kill*(1) command).

If a SIGHUP signal is received during network interface capture, *compactor* will
stop the current collection, re-read the configuration file and restart data collection
using updated settings. Only configuration items previously unspecified or taken
from the configuration file can be updated; items specified on the command line
cannot be changed. During restart there will be a brief interval during which packets
are not recorded.

Reading packets from a network interface may require that you have
special privileges; see the *pcap*(3PCAP) man page for details.

*compactor* will report an error if no input file or network interface device is
specified.

== OPTIONS

Options to *compactor* are command options or configuration options.

=== Command options

Command options are given on the command line.

*-h, --help*::
  Print a usage message briefly summarising these command-line options and then exit.

*-v, --version*::
  Print the version number of *compactor* to the standard output stream and then exit.

*-r. --report-info* [_arg_]::
  Report info (config and statistics summary) on exit. _arg_ may be
  `true` or `1` to enable promiscucous mode, `false` or `0` to disable
  promiscuous mode. If _arg_ is omitted, it defaults to `true`.

*-l, --list-interfaces*::
  List all network interfaces from which DNS traffic may be captured.

*-c, --configfile*::
  The configuration file to read. If not specified, the default configuration file
 `/etc/dns-stats-compactor/compactor.conf` is read if present.

*--debug-dns*::
   Print a summary of each DNS packet to standard output after decoding.

*--debug-qr*::
   Print a summary of each query/response pair to standard output after matching
   query and response.

=== Configuration options

Configuration options may be given on the command line, or may be specified in a
configuration file. The same option may be given in a configuration file and also on the
command line, in which case the command line option value is used.

A configuration file is a plain text file with lines in the form `option=value`. A `#`
character introduces a comment that spans until the end of the line.

In a configuration file, the long form of the option name must be used. So, for
example, to set the snap length to 64, the configuration file entry must read
`snaplen=64`. `s=64` will not be accepted.

==== Capture from network

*-i, --interface* _arg_::
  Capture traffic from network interface _arg_. This argument may be given multiple
  times to allow capture for several interfaces in parallel.

*-S, --server-address-hint* _arg_::
  _arg_ is a single IPv4 or IPv6 address for the server. These hints are optional, do not
  affect capture in any way, but are stored in C-DNS as a potential aide to
  post-capture analysis. If capture from one or more interfaces is specified, then
  a sanity check is performed to ensure the address is be present on a system
  interface; if not, an error is logged, but collection proceeds. This argument may
  be given multiple times.

*-f, --filter* _arg_::
  Discard packets not matching the filter expression _arg_. The filter syntax is described
  in *pcap-filter*(7). Packets are discarded at the point of capture; discarded packets
  do not appear in any ignored PCAP output file.

*-s, --snaplen* _arg_::
  Capture up to _arg_ bytes per packet. The default is 65535.

*-p, --promiscuous-mode* [_arg_]:: Put the interface into promiscuous
  mode. _arg_ may be `true` or `1` to enable promiscucous mode,
  `false` or `0` to disable promiscuous mode. If _arg_ is omitted, it
  defaults to `true`. Promiscuous mode is disabled by default.

*-a, --vlan-id* _arg_::
  ID of VLAN to be captured if on a 802.1Q network. The argument may be given
  multiple times to capture from several VLANs. If no *vlan-id* argument is given,
  traffic is captured from all VLANs.

*-L, --log-network-stats-period* _arg_::
  Every _arg_ seconds, log basic statistics on packet collection to the system log. The
  default value of 0 disables this logging.

==== Outputs

*-o, --output* _PATTERN_::
  Use _PATTERN_ as the template for the file path for the C-DNS output files. If no output
  pattern is given, no output is written.

*-z, --gzip-output* [_arg_]::
  Compress data in the C-DNS output files using gzip(1) format. _arg_ may be
  `true` or `1` to  enable compression, `false` or `0` to disable compression.
  If _arg_ is omitted,  it defaults to `true`. If compression is enabled, an
  extension `.gz` is added to  the output filename.

*-y, --gzip-level* [_arg_]::
  Compression level to use when producing gzip(1) C-DNS output. _arg_ must be
  a single digit `0` to `9`.  If not specified, the default level is `6`.

*-x, --xz-output* [_arg_]::
  Compress data in the C-DNS output files using xz(1) format. _arg_ may be `true`
  or `1` to enable compression, `false` or `0` to disable compression. If _arg_ is omitted,
  it defaults to `true`. If compression is enabled, an extension `.xz` is added to
  the output filename.

*-u, --xz-preset* [_arg_]::
  Compression preset level to use when producing xz(1) C-DNS output. _arg_ must be
  a single digit `0` to `9`.  If not specified, the default level is `6`.

*--max-compression-threads* [_arg_]::
  Maximum number of threads to use when compressing. Compression uses
  one thread per output file, so this argument gives the number of
  output files that can be compressed simultaneously. _arg_ must be
  `1` or more.  If not specified, the default number of threads is `2`.

*-w, --raw-pcap* _PATTERN_::
  Use _PATTERN_ as the template for a file path for output of all packets captured to
  file in PCAP format. If no pattern is given, no raw packet output is written.

*-m, --ignored-pcap* _PATTERN_::
  Use _PATTERN_ as the template for a file path for output of all packets captured that
  were not to the configured DNS ports, or were not validly formed DNS packets.
  If no pattern is given, no ignored packet output is written.

*-Z, --gzip-pcap* [_arg_]::
  Compress data in the PCAP output files using gzip(1) format. _arg_ may be
  `true` or `1` to  enable compression, `false` or `0` to disable compression.
  If _arg_ is omitted,  it defaults to `true`. If compression is enabled, an
  extension `.gz` is added to  the output filename.

*-Y, --gzip-level-pcap* [_arg_]::
  Compression level to use when producing gzip(1) PCAP output. _arg_ must be
  a single digit `0` to `9`.  If not specified, the default level is `6`.

*-X, --xz-pcap* [_arg_]::
  Compress data in the PCAP output files using xz(1) format. _arg_ may be `true`
  or `1` to enable compression, `false` or `0` to disable compression. If _arg_ is omitted,
  it defaults to `true`. If compression is enabled, an extension `.xz` is added to
  the output filename.

*-U, --xz-preset-pcap* [_arg_]::
  Compression preset level to use when producing xz(1) C-DNS output. _arg_ must be
  a single digit `0` to `9`.  If not specified, the default level is `6`.

*-t, --rotation-period* _SECONDS_::
  Specify the frequency with which all output file path patterns should be re-examined.
  If the file path has changed, the existing output file is closed and a new one opened
  using the new pattern expansion. If the file path has not changed, the pattern
  is re-examined every second until it changes. The default period is 300 seconds.
  This may be combined with maximum output file size rotation, in which case
  rotation happens when either condition is met.

*-n, --include* _SECTIONS_::
  Indicate which optional sections should be included in the main output. This argument
  can be given multiple times. By default none of these optional sections are included.

*-g, --ignore-rr-type* _TYPE_::
   Indicate an RR type _TYPE_ that should not be included in the main output.
   The first question is always included, but _TYPE_ nominated using the RR type
   name (in upper case)  will be omitted from any other question and from
   any Answer, Authority or  Additional section. This argument can be given
   multiple times.

*-e, --accept-rr-type* _TYPE_::
   Indicate RR type _TYPE_ should be included in the main output. The first question
   is always included, but only _TYPE_ nominated using the RR type name
   (in upper case) will be included in any other question and in any Answer,
   Authority or Additional section. This argument can be given multiple times.

*--max-block-qr-items* _arg_::
   Set the maximum number of query/response items included in a single
   output C-DNS block. _arg_ must be a positive integer. The default maximum
   size is 5000.

*--max-output-size* _arg_::
   Sets a maximum size for the uncompressed output before an output file
   rotation is triggered. _arg_ must be a positive integer, and may optionally
   be followed by one of the following multiplicative suffixes: _k_=1024, _K_=1000,
   _m_=1024*1024, _M_=1000*1000 and similarly for _g_, and _t_.
   If a file rotation is triggered, the remaining block and the file postlude will
   be written, so the final file size will exceed this setting by a small margin. The
   default value is 0, which indicates there is no maximum size.
   This may be combined with a rotation period, in which case
   rotation happens when either condition is met.

==== Query/response matching

*-q, --query-timeout* _SECONDS_::
  If no response is found for a query after _SECONDS_, time out the query. The default
  timeout is 5 seconds.

*-k, --skew-timeout* _MICROSECONDS_::
  Due to the vagaries of the network stack, it is possible for responses to be reported
  before the matching query, even though the query has an earlier timestamp than
  the response. A response is not considered to be missing a query until
  after _MICROSECONDS_. The default  timeout is 10 microseconds.

== OUTPUT FILE PATTERNS

The paths used for all types of file output are described with output
patterns. An output pattern can include expansions introduced by a `%`
character in the filename part of the path (i.e. the last component -
you can't have expansions in a directory name). `%%` adds a single `%`
character to the output path.

Two categories of expansions are available, time expansions and configuration
expansions. Time expansions are of the form `%` followed by a single letter, and
expand to a time component determined by the letter. For a list of the available letters,
see *strftime*(3).

Configuration expansions are of the form `%{name}`, and substitute the value of the
configuration item named. The configuration items that may be substituted are
*interface*, *rotate-period*, *snaplen*, *query-timeout*, *skew-timeout*, and
*promiscuous-mode*. *interface* substitutes the names of all configured
interfaces separated by *-* . The first network interface can be substituted as
*interface1* , a second network interface (if configured) can be substituted
as *interface2*, and so on. Similarly, *vlan-id* substitutes all configured VLAN IDs
separated by *-*. The first VLAN ID can be substituted as *vlan1*, *vland-id2*
substitutes the second VLAN ID if configured, and so on.

== OUTPUT FILE SECTIONS

The main output of DNS Query/Response pair information can optionally include
full details on sections of the DNS messages.

*query-questions*::
  Include second and subsequent QUESTION sections from queries. The first
  QUESTION section is always recorded.

*query-answers*::
  Include ANSWERS data from queries.

*query-authority*::
  Include AUTHORITY data from queries.

*query-additional*::
  Include ADDITIONAL data from queries.

*query-all*::
  Include all sections from queries.

*response-questions*::
  Include second and subsequent QUESTION sections from responses. The first
  QUESTION section is always recorded.

*response-answers*::
  Include ANSWERS data from responses.

*response-authority*::
  Include AUTHORITY data from responses.

*response-additional*::
  Include ADDITIONAL data from responses.

*response-all*::
  Include all sections from queries.

*all*::
  Include all sections from both queries and responses.

== EXIT STATUS

The exit status is 1 if any error occurred. A successful run ends with an exit status of 0.

== RESOURCES

There will be a website one day.

== COPYRIGHT

Copyright 2016-2017 Internet Corporation for Assigned Names and Numbers.

Free use of this software is granted under the terms of the Mozilla Public
Licence, version 2.0. See the source for full details.
