== Configuring

Many _compactor_ settings for capturing and storing traffic can be set
using the _compactor_ configuration file. Additionally, binary package
installations of _compactor_ install support for running the
compactor as a daemon, and these typically restrict the system
resources available to _compactor_ .

_inspector_  has no configuration file. Only command line arguments
can be used to control _inspector_ .

=== _compactor_ configuration file

==== Configuration file location

On startup, _compactor_ attempts to read a configuration file. By
default this is named `compactor.conf`, and is located in a
`dns-stats-compactor` system configuration directory.

If installed from a binary package on Linux, the configuration file
will be at `/etc/dns-stats-compactor/compactor.conf`.

===== Default configuration

Both installing via binary packages and installing using the source distribution
will install a sample `compactor.conf` configuration
file. This needs to be edited to specify an interface to collect from,
but is otherwise configured to collect traffic:

* Recording all DNS additional sections
* Writing C-DNS output compressed with `xz` compression
* Naming output files named with the date, time, rotating period and capture interface. 
* A new output file is commenced every 5 minutes.
* The 'raw' traffic is also recorded to a PCAP output file
* The 'ignored' traffic is also recorded to a PCAP output file
* The output files are stored under `/var/lib/dns-stats-compactor`
in subdirectories `cdns`, `pcap/raw` and `pcap/ignored`.

An alternate path for the configuration file can be specified to the
compactor using the *-c, --configfile* command line option.

All configuration items can also be specified on the command line. 

IMPORTANT: If an option appears in the configuration file and on the command line, the
command line setting overrides the configuration file.

==== Configuration file format

A configuration file is a plain text file with lines in the form `option=value`. A `#`
character introduces a comment that spans until the end of the line. To illustrate,
here's an extract from a possible configuration file:

[source,ini]
----
# Interface on which to capture traffic.
interface=eth0

# VLAN IDs to capture. If none specified, all are captured.
# vlan-id=

# Snap length - limit of bytes in package to capture.
snaplen=5000

# Enable promiscuous mode.
promiscuous-mode=true
----

On the command line, configuration options may be specified in short and long
forms. In a configuration file, the long form of the option name must be used. So, for
example, to set the snap length to 64, the configuration file entry must read
`snaplen=64`. `s=64` will not be accepted.

==== Configuration file options

Full details of the options that may be used in a configuration file
are in the _compactor_ manual page, *compactor*(1).

This section highlights the basic options that need to be set for a typical
simple collection, and gives a sample of usage of each.

===== Capture from network

*interface*=_arg_::
  Capture traffic from network interface _arg_. This argument may be given multiple
  times to allow capture for several interfaces in parallel.

[source,ini]
----
# Collect from eth0 and eth1.
interface=eth0
interface=eth1
----

*vlan-id*=_arg_::
  ID of VLAN to be captured if on a 802.1Q network. The argument may be given
  multiple times to capture from several VLANs. If no *vlan-id* setting is given,
  traffic is captured from all VLANs.

[source,ini]
----
vlan-id=10
----

===== Output file patterns

Output files, C-DNS and PCAP, are named using output file
patterns. These are made up from a directory path and an output
filename. So, for example, a PCAP output file might be named
`/tmp/pcap/output.pcap`. In this example, `/tmp/pcap/` is the
directory path, and `output.pcap` is the output filename.

Output filenames can contain expansion patterns. Expansion patterns
are introduced by a `%` character, and are of two basic types, time
expansions and configuration expansions.

[cols="2*"]
|===
| `%` followed by a single letter
| Insert a time expansion.

| `%{name}`
| Insert the current value of the configuration item `name`

| `%%`
| Insert a single `%` in the output filename.
|===

The full list of letters available in the time expansion, and what
they expand to, is in the *strftime*(3) manual page. Some of the
commonly used ones are given below, with expansions for a date and
time of Monday January 16th 2017 at 13:18:05.

[cols="3*"]
|===
| `%y`
| The year, not including the century.
| `17`

| `%Y`
| The year, including the century.
| `2017`

| `%C`
| The century part of the year.
| `20`

| `%m`
| The month as  a decimal number (01-12).
| `1`

| `%d`
| The day of the month as  a decimal number (01-31).
| `16`

| `%w`
| The day of the week as  a decimal number (0-6). Sunday is 0.
| `1`

| `%W`
| The week number (00-53).
| `03`

| `%H`
| The hour (24-hour clock) as a decimal number (00-23).
| `13`

| `%M`
| The minute as a decimal number (00-59).
| `18`

| `%S`
| The second as a decimal number (00-59).
| `05`
|===

Not all configuration items can be used in a configuration expansion. The
items that can be used are as follows.

[cols="3*"]
|===
| `%{interface1}`
| The name of the first configured interface. `interface2` gives the second
interface, `interface3` the third and so on.
| `eth0`

| `%{interface}`
| The names of all configured interfaces separated by `-`.
| `eth0-eth1`

| `%{rotate-period}`
| The file rotation period, in seconds.
| `300`

| `%{snaplen}`
| The network capture snap length.
| `65535`

| `%{query-timeout}`
| The query timeout, in seconds. If no response to a query arrives by the timeout,
the query is treated as unanswered.
| `5`

| `%{skew-timeout}`
| The skew timeout, in microseconds. If a response arrives without a query, it is
held for the timeout period to see if a query arriving just after matches.
| `10`

| `%{promiscuous-mode}`
| Outputs `1` if the network interfaces are in promiscuous mode, `0`
otherwise.
| `true`

| `%{vlan-id1}`
| The ID of the first configured VLAN. `vlan-id2` gives the second
configured VLAN ID, `vlan-id3` the third and so on.
| `eth0`

| `%{vlan-id}`
| The IDs of all configured VLANs separated by `-`.
| `10-12`
|===

===== Output file options

*output*=_PATTERN_::
  Use _PATTERN_ as the template for the file path for the C-DNS output files. If no output
  pattern is given, no output is written.

[source,ini]
----
output=/tmp/cdns/%Y%m%d-%H%M%S_%{rotate_period}_%{interface}.cdns
----

Using the above date and time, a rotation period of 300s and
collecting from interfaces `eth0` and `eth1` this will write to
`/tmp/cdns/20170116-131805_300_eth0-eth1.cdns`.

*xz-output*=_arg_::
  Compress data in the C-DNS output files using xz(1) format. _arg_ may be `true`
  or `1` to enable compression, `false` or `0` to disable compression.
  If compression is enabled, an extension `.xz` is added to the output filename.

[source,ini]
----
xz-output=true
----

*xz-preset*=_arg_::
  Compression preset level to use when producing xz(1) C-DNS output. _arg_ must be
  a single digit `0` to `9`.  If not specified, the default level is `6`.

[source,ini]
----
xz-preset=3
----

*raw-pcap*=_PATTERN_::
  Use _PATTERN_ as the template for a file path for output of all packets captured to
  file in PCAP format. If no pattern is given, no raw packet output is written.

[source,ini]
----
raw-pcap=/tmp/pcap/%Y%m%d-%H%M%S_%{rotate_period}_%{interface}.raw.pcap
----

Using the above date and time, a rotation period of 300s and
collecting from interfaces `eth0` and `eth1` this will write to
`/tmp/pcap/20170116-131805_300_eth0-eth1.raw.pcap`.

*ignored-pcap*=_PATTERN_::
  Use _PATTERN_ as the template for a file path for output of all packets captured that
  were not to the configured DNS ports, or were not validly formed DNS packets.
  If no pattern is given, no ignored packet output is written.

[source,ini]
----
ignored-pcap=/tmp/pcap/%Y%m%d-%H%M%S_%{rotate_period}_%{interface}.ignored.pcap
----

Using the above date and time, a rotation period of 300s and
collecting from interfaces `eth0` and `eth1` this will write to
`/tmp/pcap/20170116-131805_300_eth0-eth1.ignored.pcap`.

*xz-pcap*=_arg_::
  Compress data in the PCAP output files using xz(1) format. _arg_ may be `true`
  or `1` to enable compression, `false` or `0` to disable compression.
  If compression is enabled, an extension `.xz` is added to the output filename.

[source,ini]
----
xz-pcap=true
----

*xz-preset-pcap*=_arg_::
  Compression preset level to use when producing xz(1) C-DNS output. _arg_ must be
  a single digit `0` to `9`.  If not specified, the default level is `6`.

[source,ini]
----
xz-preset-pcap=3
----

*rotation-period*=_SECONDS_::
  Specify the frequency with which all output file path patterns should be re-examined.
  If the file path has changed, the existing output file is closed and a new one opened
  using the new pattern expansion. If the file path has not changed, the pattern
  is re-examined every second until it changes. The default period is 300 seconds.

[source,ini]
----
rotation-period=300
----

*--max-compression-threads* =_arg_::
  Maximum number of threads to use when compressing. Compression uses
  one thread per output file, so this argument gives the number of
  output files that can be compressed simultaneously. _arg_ must be
  `1` or more.  If not specified, the default number of threads is `2`.

[source,ini]
----
max-compression-threads=2
----

===== C-DNS options

*include*=_SECTIONS_:: Indicate which optional sections should be
  included in the C-DNS output. This argument can be given multiple
  times. By default none of these optional sections are included.

[cols="2*",options="header"]
|===
| Section name
| Description

| query-questions
|   Include second and subsequent QUESTION sections from queries. The first
  QUESTION section is always recorded.

| query-answers
|  Include ANSWERS data from queries.

| query-authority
| Include AUTHORITY data from queries.

| query-additional
| Include ADDITIONAL data from queries.

| query-all
| Include all sections from queries.

| response-questions
| Include second and subsequent QUESTION sections from responses. The first
  QUESTION section is always recorded.

| response-answers
| Include ANSWERS data from responses.

| response-authority
| Include AUTHORITY data from responses.

| response-additional
|  Include ADDITIONAL data from responses.

| response-all
| Include all sections from queries.

| all
| Include all sections from both queries and responses.

|===

[source,ini]
----
include=all
----
=== _compactor_ excluded fields file

You can control what fields are included in the C-DNS output via entries in the `excluded_fields.conf` file

==== Excluded fields file location

On startup, _compactor_ looks for a excluded fields file. By default this is named `excluded_fields.conf`, and is located in a `dns-stats-compactor` system configuration directory.

If installed from a binary package on Linux, the configuration file will be at `/etc/dns-stats-compactor/excluded_fields.conf`

==== Default configuration

Both installing via binary packages and installing using the source distribution will install a sample
`excluded_fields.conf` file. This file lists fields to be excluded from the C-DNS output.
By default this file contains all the field names commented out so all fields are collected in the C-DNS.
The fields are specified in logical groups.

=== Configuring _compactor_ daemon startup

All binary packages of _compactor_ include startup setup allowing
_compactor_ to be run as a daemon, and possibly started
automatically on boot.

These startup setups may also contain settings constraining the
compactor's use of memory and CPU.

==== Linux with `systemd`

By default, http://releases.ubuntu.com/16.04/[Ubuntu 16.04 LTS 'Xenial
Xerus'] uses `systemd`.

===== Running as a daemon

Binary packages for Ubuntu 16.04 include a `systemd` service file with
the setup information required to run _compactor_ as a daemon.

When installing on Debian-based systems such as Ubuntu, installing the package
will automatically enable the service and attempt to start _compactor_ , or restart
it if already running.

To enable the service, use the `systemctl enable` subcommand.

----
# systemctl enable dns-stats-compactor
----

To start or stop the daemon, or request it reload its configuration, use the
appropriate `systemctl` subcommand.

===== Changing resource restrictions

This file includes `CPUAffinity` and `MemoryLimit` clauses to restrict
_compactor_ to particular CPUs and limit its memory usage. In the
installed service file, these are set to CPU 0 only and 1Gb
respectively.

[source,ini]
----
[Service]
CPUAffinity=0
MemoryLimit=1G
----

To override these, use the `systemctl edit` subcommand to create a service
file override unit with an updated version of the above snippet.
